# Todo .env
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - '3001:3000'
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL} #postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: ${DATABASE_TYPE} # postgresql
      APP_SECRET: ${APP_SECRET} #replace-me-with-a-random-string
    init: true
    restart: always
    networks:
    - postgres
#    network_mode: "bridge"  
networks:
  - postgres_net
