services:
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyterlab
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - jupyter_data:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: 1000
      NB_GID: 1000

volumes:
  jupyter_data:
    driver: local
