# Todo .env
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      DATABASE_TYPE: postgresql
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET: ${APP_SECRET} 
    init: true
    restart: always
    network_mode: "host"  
#networks:
 # - postgres_net
